cargo-features = ["edition2024"]

[package]
name = "pxsol-ss-pinocchio"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = "0.9.2"
pinocchio-system = "0.3.0"
